import React, { useState } from 'react';
import { useQuery } from 'react-query';
import axios from 'react-query';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'text/javascript';
import { useAuth } from '../contexts/AuthContext';
            </Box>
          </Card>
        </Grid>
      </Grid>
    </Box>
  );
};

export default ResumeUpload;
